# This file is auto-generated by the build process.
# Do not edit manually.
# During development it returns 'dev'.
# In packaged builds it is overwritten by CI with the real version.

__version__ = "dev"
